/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projectEuler;

import org.junit.Test;
import static org.junit.Assert.*;

public class Problem19Test {
    @Test public void testSomeLibraryMethod() {
        var expected = 0;
        var actual = Problem19.getAnswer();
        assertEquals("Problem 19 returns the correct answer", expected, actual);
    }
}
