(* Problem 2: Even Fibonacci Numbers
    
Each new term in the Fibonacci sequence is generated by adding the 
previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values 
do not exceed four million, find the sum of the even-valued terms.

*)

module Problem2

let fib =
    (0, 1) 
    |> Seq.unfold (fun (cur, next) -> Some(cur, (next, cur + next)))

let getAnswer =
    fib
    |> Seq.takeWhile (fun n -> n <= 4000000)
    |> Seq.filter(fun n -> n % 2 = 0)
    |> Seq.sum

(*

https://lookingsharp.wordpress.com/2010/02/27/fibonacci-fun-with-fsharp/

You are the 572202nd person to have solved this problem.

*)